name: Go

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -ldflags="-s -w" -v .

      - name: Test
        run: go test -v .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker images to Docker Hub
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: martinplaner/mp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
